# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400)),
                ('published', models.BooleanField(default=False)),
                ('cat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='accalascio.Category')),
            ],
        ),
    ]
