# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accalascio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
