# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accalascio', '0002_post_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='active',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='Mannaggia', max_length=80),
            preserve_default=False,
        ),
    ]
