# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:00
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accalascio', '0004_post_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
