# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accalascio', '0005_auto_20161125_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='rangeCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='interval',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='icon',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='endcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postEnd', to='accalascio.rangeCat'),
        ),
        migrations.AddField(
            model_name='post',
            name='startcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postStart', to='accalascio.rangeCat'),
        ),
    ]
