# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accalascio', '0006_auto_20161128_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='iconCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('png', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postStart', to='accalascio.iconCat'),
        ),
    ]
