# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accalascio', '0008_auto_20161128_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='roomFac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('png', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='renting',
            name='facilites',
            field=models.ManyToManyField(blank=True, related_name='rent', to='accalascio.roomFac'),
        ),
    ]
