# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accalascio', '0011_auto_20161128_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgrent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='renting',
            name='png',
        ),
        migrations.AddField(
            model_name='imgrent',
            name='description',
            field=models.TextField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='imgrent',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accalascio.Renting'),
        ),
        migrations.AddField(
            model_name='renting',
            name='icon',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='imgrent',
            name='content',
            field=models.ImageField(upload_to=''),
        ),
    ]
