# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accalascio', '0013_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
